[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
]

[profile.default.fuzz]
runs = 256

# Lisk Sepolia Testnet
[rpc_endpoints]
lisk_sepolia = "${LISK_SEPOLIA_RPC_URL}"
lisk_mainnet = "${LISK_MAINNET_RPC_URL}"

# Etherscan/Blockscout verification
[etherscan]
lisk_sepolia = { key = "${BLOCKSCOUT_API_KEY}", url = "https://sepolia-blockscout.lisk.com/api" }
lisk_mainnet = { key = "${BLOCKSCOUT_API_KEY}", url = "https://blockscout.lisk.com/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
